spring:
  application:
    name: platform-core
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: NON_NULL

logging:
  pattern:
    level: "%5p [%X{requestId}, %X{sessionId}, %X{clientIp}]"
  level:
    com.esgbank.greenbond: DEBUG
